version: "3.3"

services:

  micro-api:
    build:
      context: ./
      dockerfile: Dockerfile
      
    container_name: micro-api
    ports:
      - '3001:3000'

    stdin_open: true
    tty: true    

